/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *button1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *button4;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *button5;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label39;
  GtkWidget *button2;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *Modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button13;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label53;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 336, 64);
  gtk_widget_set_size_request (treeview1, 600, 416);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 80, 64);
  gtk_widget_set_size_request (button1, 136, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("<span color=\"#855969\"><u>Gestion des capteurs</u></span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 304, 16);
  gtk_widget_set_size_request (label1, 279, 30);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 80, 448);
  gtk_widget_set_size_request (button4, 136, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 80, 352);
  gtk_widget_set_size_request (button5, 136, 64);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button5), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Affiche"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 80, 256);
  gtk_widget_set_size_request (button2, 136, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button2), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  Modifier = gtk_button_new ();
  gtk_widget_show (Modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), Modifier, 80, 160);
  gtk_widget_set_size_request (Modifier, 136, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed1), button13, 488, 488);
  gtk_widget_set_size_request (button13, 256, 64);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button13), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Capteur defectueux"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox15), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_capteur_defectueux_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label3, "label3");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, button4, "button4");
  GLADE_HOOKUP_OBJECT (acceuil, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (acceuil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (acceuil, image5, "image5");
  GLADE_HOOKUP_OBJECT (acceuil, label6, "label6");
  GLADE_HOOKUP_OBJECT (acceuil, button5, "button5");
  GLADE_HOOKUP_OBJECT (acceuil, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (acceuil, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (acceuil, image14, "image14");
  GLADE_HOOKUP_OBJECT (acceuil, label39, "label39");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (acceuil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (acceuil, image4, "image4");
  GLADE_HOOKUP_OBJECT (acceuil, label5, "label5");
  GLADE_HOOKUP_OBJECT (acceuil, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (acceuil, label4, "label4");
  GLADE_HOOKUP_OBJECT (acceuil, button13, "button13");
  GLADE_HOOKUP_OBJECT (acceuil, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (acceuil, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (acceuil, image15, "image15");
  GLADE_HOOKUP_OBJECT (acceuil, label53, "label53");

  return acceuil;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed2;
  GtkWidget *entry3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label17;
  GtkWidget *entry10;
  GtkWidget *combobox3;
  GtkWidget *button6;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label35;
  GtkWidget *button7;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label34;
  GtkWidget *combobox1;
  GtkWidget *combobox2;
  GtkWidget *label13;
  GtkWidget *label26;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *label36;
  GtkWidget *label16;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *combobox7;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("Ajouter un capteur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout), fixed2);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 152, 56);
  gtk_widget_set_size_request (entry3, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  spinbutton1_adj = gtk_adjustment_new (0, 0, 500, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 152, 384);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label17 = gtk_label_new_with_mnemonic (_("<span color=\"#008856\"><u> Ajout</u></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 152, 8);
  gtk_widget_set_size_request (label17, 304, 25);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed2), entry10, 152, 128);
  gtk_widget_set_size_request (entry10, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox3, 280, 192);
  gtk_widget_set_size_request (combobox3, 80, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2023"));

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 152, 448);
  gtk_widget_set_size_request (button6, 120, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button6), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox12), label35, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 312, 448);
  gtk_widget_set_size_request (button7, 120, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button7), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox11), label34, FALSE, FALSE, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 152, 192);
  gtk_widget_set_size_request (combobox1, 48, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("31"));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox2, 216, 192);
  gtk_widget_set_size_request (combobox2, 48, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("12"));

  label13 = gtk_label_new (_("Reference:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 40, 56);
  gtk_widget_set_size_request (label13, 112, 25);

  label26 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 48, 128);
  gtk_widget_set_size_request (label26, 112, 25);

  label11 = gtk_label_new (_("Date :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 56, 192);
  gtk_widget_set_size_request (label11, 112, 25);

  label12 = gtk_label_new (_("Etage :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 48, 328);
  gtk_widget_set_size_request (label12, 120, 24);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("1er"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 152, 328);
  gtk_widget_set_size_request (radiobutton1, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label36 = gtk_label_new (_("Type :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed2), label36, 48, 264);
  gtk_widget_set_size_request (label36, 128, 25);

  label16 = gtk_label_new (_("Valeur :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 48, 384);
  gtk_widget_set_size_request (label16, 120, 25);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("2eme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 224, 328);
  gtk_widget_set_size_request (radiobutton2, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("3eme"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 312, 328);
  gtk_widget_set_size_request (radiobutton3, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("4eme"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 400, 328);
  gtk_widget_set_size_request (radiobutton4, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("5eme"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton5, 480, 328);
  gtk_widget_set_size_request (radiobutton5, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox7, 152, 256);
  gtk_widget_set_size_request (combobox7, 152, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Temp\303\251rature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Humidit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("D\303\251bit_d'eau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Fum\303\251e"));

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_back1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajout, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajout, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajout, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (ajout, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (ajout, button6, "button6");
  GLADE_HOOKUP_OBJECT (ajout, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (ajout, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ajout, image12, "image12");
  GLADE_HOOKUP_OBJECT (ajout, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajout, button7, "button7");
  GLADE_HOOKUP_OBJECT (ajout, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ajout, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajout, image11, "image11");
  GLADE_HOOKUP_OBJECT (ajout, label34, "label34");
  GLADE_HOOKUP_OBJECT (ajout, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajout, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajout, label26, "label26");
  GLADE_HOOKUP_OBJECT (ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajout, label36, "label36");
  GLADE_HOOKUP_OBJECT (ajout, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (ajout, combobox7, "combobox7");

  return ajout;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *button9;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label9;
  GtkWidget *hseparator2;
  GtkWidget *label18;
  GtkWidget *label7;
  GtkWidget *button8;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer un capteur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 192, 88);
  gtk_widget_set_size_request (entry1, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 248, 160);
  gtk_widget_set_size_request (button9, 128, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button9), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox7), label9, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator2, 0, 48);
  gtk_widget_set_size_request (hseparator2, 472, 16);

  label18 = gtk_label_new_with_mnemonic (_("<span color=\"#008856\"><u> Suppression</u></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 160, 16);
  gtk_widget_set_size_request (label18, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label7 = gtk_label_new (_("Reference :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 80, 88);
  gtk_widget_set_size_request (label7, 136, 32);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 88, 160);
  gtk_widget_set_size_request (button8, 128, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button8), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_back2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_sup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimer, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (supprimer, button9, "button9");
  GLADE_HOOKUP_OBJECT (supprimer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (supprimer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (supprimer, image7, "image7");
  GLADE_HOOKUP_OBJECT (supprimer, label9, "label9");
  GLADE_HOOKUP_OBJECT (supprimer, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (supprimer, label18, "label18");
  GLADE_HOOKUP_OBJECT (supprimer, label7, "label7");
  GLADE_HOOKUP_OBJECT (supprimer, button8, "button8");
  GLADE_HOOKUP_OBJECT (supprimer, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (supprimer, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (supprimer, image6, "image6");
  GLADE_HOOKUP_OBJECT (supprimer, label8, "label8");

  return supprimer;
}

GtkWidget*
create_modif (void)
{
  GtkWidget *modif;
  GtkWidget *fixed4;
  GtkWidget *entry2;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *entry5;
  GtkWidget *button12;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label33;
  GtkWidget *label24;
  GtkWidget *label45;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label50;
  GtkWidget *label49;
  GtkWidget *label46;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton9;
  GtkWidget *radiobutton10;
  GtkWidget *hseparator1;
  GtkWidget *label1;
  GtkWidget *label29;
  GtkWidget *label27;
  GtkWidget *label2;
  GtkWidget *button10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label31;
  GtkWidget *button11;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label32;
  GtkWidget *combobox4;
  GtkWidget *combobox5;
  GtkWidget *combobox6;
  GtkWidget *combobox8;

  modif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif), _("Modifier un capteur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modif), fixed4);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed4), entry2, 208, 56);
  gtk_widget_set_size_request (entry2, 192, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton2_adj = gtk_adjustment_new (0, 0, 500, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 136, 440);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 136, 144);
  gtk_widget_set_size_request (entry5, 168, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 424, 56);
  gtk_widget_set_size_request (button12, 112, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button12), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox10), label33, FALSE, FALSE, 0);

  label24 = gtk_label_new ("");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 248, 112);
  gtk_widget_set_size_request (label24, 160, 16);

  label45 = gtk_label_new (_("Reference:"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed4), label45, 64, 56);
  gtk_widget_set_size_request (label45, 144, 41);

  label47 = gtk_label_new (_("Date :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 16, 224);
  gtk_widget_set_size_request (label47, 129, 25);

  label48 = gtk_label_new (_("Etage :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed4), label48, 32, 368);
  gtk_widget_set_size_request (label48, 120, 25);

  label50 = gtk_label_new (_("Valeur :"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 8, 440);
  gtk_widget_set_size_request (label50, 144, 24);

  label49 = gtk_label_new (_("Type :"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed4), label49, 48, 304);
  gtk_widget_set_size_request (label49, 80, 25);

  label46 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed4), label46, 24, 144);
  gtk_widget_set_size_request (label46, 112, 33);

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("1er"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton6, 136, 368);
  gtk_widget_set_size_request (radiobutton6, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("2eme"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton7, 200, 368);
  gtk_widget_set_size_request (radiobutton7, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("3eme"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton8, 272, 368);
  gtk_widget_set_size_request (radiobutton8, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("4eme"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton9, 344, 368);
  gtk_widget_set_size_request (radiobutton9, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("5eme"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton10, 416, 368);
  gtk_widget_set_size_request (radiobutton10, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator1, 24, 104);
  gtk_widget_set_size_request (hseparator1, 536, 16);

  label1 = gtk_label_new (_("........."));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed4), label1, 296, 296);
  gtk_widget_set_size_request (label1, 80, 32);

  label29 = gtk_label_new (_("........."));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 344, 224);
  gtk_widget_set_size_request (label29, 80, 32);

  label27 = gtk_label_new (_("......."));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 488, 368);
  gtk_widget_set_size_request (label27, 64, 25);

  label2 = gtk_label_new (_("........."));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed4), label2, 200, 432);
  gtk_widget_set_size_request (label2, 80, 32);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed4), button10, 192, 496);
  gtk_widget_set_size_request (button10, 112, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox8), label31, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 352, 496);
  gtk_widget_set_size_request (button11, 112, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button11), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox9), label32, FALSE, FALSE, 0);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox4, 136, 224);
  gtk_widget_set_size_request (combobox4, 48, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("31"));

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox5, 200, 224);
  gtk_widget_set_size_request (combobox5, 48, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("12"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox6, 264, 224);
  gtk_widget_set_size_request (combobox6, 72, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("2023"));

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox8, 136, 296);
  gtk_widget_set_size_request (combobox8, 152, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Temp\303\251rature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Humidit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("D\303\251bit_d'eau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Fum\303\251e"));

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton9, "toggled",
                    G_CALLBACK (on_radiobutton9_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton10, "toggled",
                    G_CALLBACK (on_radiobutton10_toggled),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_back3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif, modif, "modif");
  GLADE_HOOKUP_OBJECT (modif, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modif, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (modif, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (modif, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (modif, button12, "button12");
  GLADE_HOOKUP_OBJECT (modif, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modif, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modif, image10, "image10");
  GLADE_HOOKUP_OBJECT (modif, label33, "label33");
  GLADE_HOOKUP_OBJECT (modif, label24, "label24");
  GLADE_HOOKUP_OBJECT (modif, label45, "label45");
  GLADE_HOOKUP_OBJECT (modif, label47, "label47");
  GLADE_HOOKUP_OBJECT (modif, label48, "label48");
  GLADE_HOOKUP_OBJECT (modif, label50, "label50");
  GLADE_HOOKUP_OBJECT (modif, label49, "label49");
  GLADE_HOOKUP_OBJECT (modif, label46, "label46");
  GLADE_HOOKUP_OBJECT (modif, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (modif, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (modif, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (modif, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (modif, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (modif, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (modif, label1, "label1");
  GLADE_HOOKUP_OBJECT (modif, label29, "label29");
  GLADE_HOOKUP_OBJECT (modif, label27, "label27");
  GLADE_HOOKUP_OBJECT (modif, label2, "label2");
  GLADE_HOOKUP_OBJECT (modif, button10, "button10");
  GLADE_HOOKUP_OBJECT (modif, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modif, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modif, image8, "image8");
  GLADE_HOOKUP_OBJECT (modif, label31, "label31");
  GLADE_HOOKUP_OBJECT (modif, button11, "button11");
  GLADE_HOOKUP_OBJECT (modif, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modif, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modif, image9, "image9");
  GLADE_HOOKUP_OBJECT (modif, label32, "label32");
  GLADE_HOOKUP_OBJECT (modif, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (modif, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (modif, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (modif, combobox8, "combobox8");

  return modif;
}

